image: debian:latest
before_script:
- bash ci/docker_install.sh
test:app:
  script:
  - cd hwapp && dotnet restore && dotnet run
  - cd ../unit-testing-using-dotnet-test/test/PrimeService.Tests && dotnet restore && dotnet test